[package]
name = "driver"
version = "0.1.0"
edition = "2021"
publish = { workspace = true }
license = { workspace = true }

[dependencies]
sqlx = { version = "^0.8", features = ["sqlite", "runtime-tokio"] }
reqwest = { version = "^0.12", features = ["json"] }